---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 600

- name: Install iproute2
  apt:
    name: iproute2
  
- name: Install curl
  apt: 
    name: curl

- name: Install ping
  apt: 
    name: iputils-ping
...